In [2]:
import numpy as np;
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [54]:
W = np.random.randint(0, 9, 4*8).reshape(4, 8)

syn_n = 1.5
syn_size = W.shape[1]
W_idx = np.arange(syn_size)
W_len = np.abs(W_idx[np.newaxis].T - W_idx)
W_len = (np.array(W_len, dtype='float') + 1) ** -syn_n

res_sum = np.sum((W.T * W_len[np.newaxis].T).T, axis=1)
res_1 = np.tensordot(W, W_len, axes=(1,1)).reshape(W.shape[0],W.shape[1])
res_dot = np.dot(W, W_len).reshape(W.shape[0],W.shape[1])
print(res_1 - res_sum)
print(res_dot - res_sum)
res_sum


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


array([[ 8.91256729,  8.38895965,  7.26529091,  5.29123059,  7.64846363,
         6.77059344,  7.46269072,  8.63082924],
       [ 6.05827543,  5.79694369, 10.78720818,  8.02966897, 13.12995324,
        14.15222536, 14.02432173,  9.65944995],
       [ 6.63373947, 12.76638295, 12.39586083, 13.8517249 ,  9.80258778,
        10.77661098, 10.19820671,  4.86547303],
       [ 4.98596371,  9.43641617,  9.7494376 ,  6.11802784,  6.01705388,
         6.02202152,  7.21590649,  3.26852186]])

In [55]:
W_len_2 = np.copy(W_len)

dW_2 = np.zeros(W.shape)
for n_idx in range(W.shape[0]):
    dW_2[n_idx] = np.dot(W[n_idx], W_len_2)
print(res_1 - dW_2)
print(res_dot - dW_2)
dW_2

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


array([[ 8.91256729,  8.38895965,  7.26529091,  5.29123059,  7.64846363,
         6.77059344,  7.46269072,  8.63082924],
       [ 6.05827543,  5.79694369, 10.78720818,  8.02966897, 13.12995324,
        14.15222536, 14.02432173,  9.65944995],
       [ 6.63373947, 12.76638295, 12.39586083, 13.8517249 ,  9.80258778,
        10.77661098, 10.19820671,  4.86547303],
       [ 4.98596371,  9.43641617,  9.7494376 ,  6.11802784,  6.01705388,
         6.02202152,  7.21590649,  3.26852186]])