In [2]:
import numpy as np;
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
W = np.random.randint(0, 9, 4*8).reshape(4, 8)

syn_n = 1.5
syn_size = W.shape[1]
W_idx = np.arange(syn_size)
W_len = np.abs(W_idx[np.newaxis].T - W_idx)
W_len = (np.array(W_len, dtype='float') + 1) ** -syn_n

res_sum = np.sum((W.T * W_len[np.newaxis].T).T, axis=1)
res_1 = np.tensordot(W, W_len, axes=(1,1)).reshape(W.shape[0],W.shape[1])
res_dot = np.dot(W, W_len) #.reshape(W.shape[0],W.shape[1])
print(res_1 - res_sum)
print(res_dot - res_sum)
res_sum


[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


array([[12.63733271, 13.34317314,  8.55247806,  8.96941114,  8.08667986,
        13.94535074, 14.39048064, 11.48991017],
       [10.77447438, 11.31290612, 13.14831148, 15.92758778, 16.00455789,
        14.01215727,  9.41137651,  5.9447042 ],
       [12.61842914, 14.782562  , 13.3798736 , 10.41348411, 11.47782393,
        12.56296953, 13.72139289, 12.26557653],
       [12.20793647, 12.86945534,  7.91047929, 11.70748575,  7.27252227,
         5.08393057,  3.77540419,  4.94350463]])

In [4]:
W_len_2 = np.copy(W_len)

dW_2 = np.zeros(W.shape)
for n_idx in range(W.shape[0]):
    dW_2[n_idx] = np.dot(W[n_idx], W_len_2)
print(res_1 - dW_2)
print(res_dot - dW_2)
dW_2

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


array([[12.63733271, 13.34317314,  8.55247806,  8.96941114,  8.08667986,
        13.94535074, 14.39048064, 11.48991017],
       [10.77447438, 11.31290612, 13.14831148, 15.92758778, 16.00455789,
        14.01215727,  9.41137651,  5.9447042 ],
       [12.61842914, 14.782562  , 13.3798736 , 10.41348411, 11.47782393,
        12.56296953, 13.72139289, 12.26557653],
       [12.20793647, 12.86945534,  7.91047929, 11.70748575,  7.27252227,
         5.08393057,  3.77540419,  4.94350463]])