In [1]:
import numpy as np;
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
W = np.random.randint(-4, 9, 4*8).reshape(4, 8)
mask = np.random.choice([0, 1], size=4*8, p=[.6, .4]).reshape(4, 8)
# print(mask)
W = W * mask
print(W.shape)
W[W != 0] = 1
WT = np.expand_dims(W, axis=1)
print(WT.shape)
WW = (WT & W)
print(WW.shape)
# print(f'{WW=}')
WW44 = np.array(WW.sum(axis=2), dtype='float')
n_zeros = np.count_nonzero(WW==0, axis=2)
print(n_zeros.shape)
print(n_zeros)
n_zeros = np.sum(WW, axis=2)
print(n_zeros.shape)
print(n_zeros)
print(WW44)
np.max(WW44) - WW44


(4, 8)
(4, 1, 8)
(4, 4, 8)
(4, 4)
[[5 6 6 7]
 [6 4 7 7]
 [6 7 5 7]
 [7 7 7 5]]
(4, 4)
[[3 2 2 1]
 [2 4 1 1]
 [2 1 3 1]
 [1 1 1 3]]
[[3. 2. 2. 1.]
 [2. 4. 1. 1.]
 [2. 1. 3. 1.]
 [1. 1. 1. 3.]]


array([[1., 2., 2., 3.],
       [2., 0., 3., 3.],
       [2., 3., 1., 3.],
       [3., 3., 3., 1.]])

In [3]:
a = np.random.randint(0,2,16)
b = np.random.randint(0,2,16)
print(a)
print(b)
a & b

[0 1 1 1 0 0 0 0 1 1 0 1 0 0 1 1]
[1 0 0 1 0 0 1 1 1 0 1 0 1 0 0 1]


array([0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1])

In [4]:
WW = np.zeros((W.shape[0], W.shape[0], W.shape[1]))

for i in range(W.shape[0]):
    for k in range(W.shape[0]):
        for j in range(W.shape[1]):
            WW[i, k, j] = np.abs(W[i][j] - W[k][j])
print(WW.shape)
WW44_2 = WW.sum(axis=2)
print(WW44_2.shape)
WW44_2

(4, 4, 8)
(4, 4)


array([[0., 3., 2., 4.],
       [3., 0., 5., 5.],
       [2., 5., 0., 4.],
       [4., 5., 4., 0.]])

In [5]:
np.sum(WW44-WW44_2)


-17.0

In [6]:
W = np.random.randint(-4, 9, 4*8).reshape(4, 8)
print(W)
WTr = 0.5 * np.mean(np.abs(W), axis=1)
W[np.where(np.abs(W) < WTr[np.newaxis].T)] = 0
np.sum(W == 0)

[[-3 -3  0  1  6  5 -2  4]
 [ 6  6  2  8  8 -1  3 -1]
 [-2  4  8  6  7  0  0  2]
 [-3  2  0  0 -4  2 -4 -3]]


9

In [47]:
size = 800
k = 1
pd = 0.4
O = np.random.randint(1, 9, size).astype('float')
RFI = np.random.choice([0, 1], size=size*size, p=[.7, .3]).reshape(size, size)

OF = O[np.newaxis].T * RFI
print(f'{O=}')
print(f'{OF=}')

ArS = np.argsort(OF, axis=0)[::-1][0:1+k]
print(f'{ArS=}')
print(f'{np.unique(ArS[0]).size=}')
print(f'{np.unique(ArS[1:1+k].flatten()).size=}')
O_idx = np.arange(O.size)
winner_idx = np.where(O_idx == ArS[0])
# print(winner_idx)
ars = ArS.T[winner_idx].T
# ArS[:, winner_idx] faster?
# print(ars)
# O[winner_idx]
# ars[0] = 1
# ars[1+k] = pd
print('win=',ars[0].flatten())
print('loose=',ars[1:1+k].flatten())

O.fill(0)
O[ars[0].flatten()] = 1
O[ars[1:1+k].flatten()] = -pd
O

O=array([1., 8., 8., 2., 6., 4., 6., 4., 7., 8., 7., 6., 2., 5., 5., 1., 8.,
       7., 7., 3., 6., 3., 4., 5., 5., 8., 1., 1., 6., 3., 4., 5., 6., 3.,
       7., 2., 2., 1., 3., 5., 4., 1., 5., 2., 7., 8., 6., 4., 8., 3., 8.,
       6., 8., 4., 2., 3., 4., 4., 1., 1., 4., 4., 7., 7., 7., 1., 4., 3.,
       3., 2., 1., 5., 4., 3., 7., 5., 5., 3., 5., 2., 1., 2., 1., 8., 4.,
       1., 4., 5., 6., 8., 6., 7., 8., 6., 6., 5., 8., 5., 7., 4., 7., 4.,
       2., 7., 6., 7., 1., 5., 4., 4., 3., 7., 3., 7., 6., 7., 1., 4., 5.,
       2., 2., 1., 8., 3., 2., 8., 5., 3., 2., 4., 4., 5., 2., 7., 8., 5.,
       6., 2., 1., 8., 8., 6., 1., 3., 6., 3., 5., 3., 4., 2., 7., 3., 5.,
       4., 3., 2., 1., 6., 3., 7., 2., 5., 7., 2., 4., 6., 4., 2., 6., 8.,
       7., 6., 5., 3., 8., 8., 1., 8., 8., 5., 8., 6., 4., 6., 1., 2., 6.,
       2., 3., 7., 3., 8., 2., 1., 5., 8., 8., 8., 8., 7., 2., 2., 6., 7.,
       6., 5., 2., 8., 7., 8., 2., 5., 8., 6., 3., 2., 5., 6., 7., 2., 4.,
       2., 4., 2., 7., 

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.