In [1]:
import numpy as np;
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [7]:
W = np.random.randint(-4, 9, 4*8).reshape(4, 8)
mask = np.random.choice([0, 1], size=4*8, p=[.6, .4]).reshape(4, 8)
# print(mask)
W = W * mask
print(W.shape)
WT = np.expand_dims(W, axis=1)
print(WT.shape)
WW = np.abs(WT * W)
print(WW.shape)
WW44 = np.array(WW.sum(axis=2), dtype='float')
n_zeros = np.count_nonzero(WW==0, axis=2)
print(n_zeros.shape)
print(n_zeros)
n_zeros = np.sum(WW==0, axis=2)
print(n_zeros.shape)
print(n_zeros)
print(WW44.shape)
WW44


(4, 8)
(4, 1, 8)
(4, 4, 8)
(4, 4)
[[4 4 7 6]
 [4 2 6 5]
 [7 6 5 6]
 [6 5 6 4]]
(4, 4)
[[4 4 7 6]
 [4 2 6 5]
 [7 6 5 6]
 [6 5 6 4]]
(4, 4)


array([[ 70.,  77.,  21.,  20.],
       [ 77., 141.,  56.,  20.],
       [ 21.,  56.,  99.,  31.],
       [ 20.,  20.,  31.,  65.]])

In [3]:
WW = np.zeros((W.shape[0], W.shape[0], W.shape[1]))

for i in range(W.shape[0]):
    for k in range(W.shape[0]):
        for j in range(W.shape[1]):
            WW[i, k, j] = np.abs(W[i][j] * W[k][j])
print(WW.shape)
WW44_2 = WW.sum(axis=2)
print(WW44_2.shape)
WW44_2

(4, 4, 8)
(4, 4)


array([[ 50.,  39.,   2.,   2.],
       [ 39., 122.,   6.,   0.],
       [  2.,   6.,   8.,   4.],
       [  2.,   0.,   4.,  20.]])

In [4]:
np.sum(WW44-WW44_2)


0.0

In [5]:
W = np.random.randint(-4, 9, 4*8).reshape(4, 8)
print(W)
WTr = 0.5 * np.mean(np.abs(W), axis=1)
W[np.where(np.abs(W) < WTr[np.newaxis].T)] = 0
np.sum(W == 0)

[[ 8 -2 -3  7  3  6  5  7]
 [ 1  1  0  6  8  3 -3  1]
 [ 5 -4  4  5  0  5  8 -4]
 [-1  8  1  2 -2  1 -1 -3]]


10