In [1]:
import numpy as np;
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [9]:
W = np.random.randint(-4, 9, 4*8).reshape(4, 8)
mask = np.random.choice([0, 1], size=4*8, p=[.6, .4]).reshape(4, 8)
# print(mask)
W = W * mask
print(W.shape)
WT = np.expand_dims(W, axis=1)
print(WT.shape)
WW = np.abs(WT - W)
print(WW.shape)
print(f'{WW=}')
WW44 = np.array(WW.sum(axis=2), dtype='float')
n_zeros = np.count_nonzero(WW==0, axis=2)
print(n_zeros.shape)
print(n_zeros)
n_zeros = np.sum(WW==0, axis=2)
print(n_zeros.shape)
print(n_zeros)
print(WW44.shape)
WW44


(4, 8)
(4, 1, 8)
(4, 4, 8)
WW=array([[[ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 2,  0,  3,  0, 10, 12,  4,  7],
        [ 0,  0,  3,  2,  0,  0,  0,  0],
        [ 0,  0,  5,  0,  4, 12,  0,  2]],

       [[ 2,  0,  3,  0, 10, 12,  4,  7],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 2,  0,  0,  2, 10, 12,  4,  7],
        [ 2,  0,  8,  0,  6,  0,  4,  5]],

       [[ 0,  0,  3,  2,  0,  0,  0,  0],
        [ 2,  0,  0,  2, 10, 12,  4,  7],
        [ 0,  0,  0,  0,  0,  0,  0,  0],
        [ 0,  0,  8,  2,  4, 12,  0,  2]],

       [[ 0,  0,  5,  0,  4, 12,  0,  2],
        [ 2,  0,  8,  0,  6,  0,  4,  5],
        [ 0,  0,  8,  2,  4, 12,  0,  2],
        [ 0,  0,  0,  0,  0,  0,  0,  0]]])
(4, 4)
[[8 2 6 4]
 [2 8 2 3]
 [6 2 8 3]
 [4 3 3 8]]
(4, 4)
[[8 2 6 4]
 [2 8 2 3]
 [6 2 8 3]
 [4 3 3 8]]
(4, 4)


array([[ 0., 38.,  5., 23.],
       [38.,  0., 37., 25.],
       [ 5., 37.,  0., 28.],
       [23., 25., 28.,  0.]])

In [10]:
WW = np.zeros((W.shape[0], W.shape[0], W.shape[1]))

for i in range(W.shape[0]):
    for k in range(W.shape[0]):
        for j in range(W.shape[1]):
            WW[i, k, j] = np.abs(W[i][j] - W[k][j])
print(WW.shape)
WW44_2 = WW.sum(axis=2)
print(WW44_2.shape)
WW44_2

(4, 4, 8)
(4, 4)


array([[ 0., 38.,  5., 23.],
       [38.,  0., 37., 25.],
       [ 5., 37.,  0., 28.],
       [23., 25., 28.,  0.]])

In [4]:
np.sum(WW44-WW44_2)


0.0

In [5]:
W = np.random.randint(-4, 9, 4*8).reshape(4, 8)
print(W)
WTr = 0.5 * np.mean(np.abs(W), axis=1)
W[np.where(np.abs(W) < WTr[np.newaxis].T)] = 0
np.sum(W == 0)

[[-4  8 -3 -1  4  7 -3  7]
 [ 7 -3  5 -2  4  0  4  3]
 [-4  6 -3  1 -1  8  5  6]
 [ 3  8  6  4  1  4  6  8]]


5

In [6]:
size = 80
k = 1
pd = 0.4
O = np.random.randint(1, 9, size).astype('float')
RFI = np.random.choice([0, 1], size=size*size, p=[.7, .3]).reshape(size, size)

OF = O[np.newaxis].T * RFI
print(f'{O=}')
print(f'{OF=}')

ArS = np.argsort(OF, axis=0)[::-1][0:1+k]
# print(f'{ArS=}')
# print(f'{ArS[0]=}')
O_idx = np.arange(O.size)
winner_idx = np.where(O_idx == ArS[0])
# print(winner_idx)
ars = ArS.T[winner_idx].T
# ArS[:, winner_idx] faster?
# print(ars)
# O[winner_idx]
# ars[0] = 1
# ars[1+k] = pd
print('win=',ars[0].flatten())
print('loose=',ars[1:1+k].flatten())

O.fill(0)
O[ars[0].flatten()] = 1
O[ars[1:1+k].flatten()] = -pd
O

O=array([7., 3., 2., 5., 6., 6., 6., 4., 7., 8., 1., 2., 2., 8., 3., 8., 8.,
       7., 5., 7., 5., 6., 2., 8., 7., 6., 5., 6., 7., 8., 1., 4., 4., 7.,
       7., 6., 3., 2., 7., 7., 8., 4., 7., 5., 3., 8., 6., 4., 5., 3., 8.,
       3., 6., 6., 6., 1., 5., 8., 5., 3., 8., 4., 4., 3., 8., 4., 1., 4.,
       6., 6., 2., 3., 1., 4., 6., 3., 4., 4., 1., 4.])
OF=array([[0., 0., 0., ..., 0., 0., 7.],
       [3., 0., 0., ..., 0., 3., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 4., ..., 0., 4., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 4., ..., 0., 4., 0.]])
win= []
loose= []


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])