In [2]:
import numpy as np;
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [3]:
W = np.random.randint(-4, 9, 4*8).reshape(4, 8)
mask = np.random.choice([0, 1], size=4*8, p=[.6, .4]).reshape(4, 8)
# print(mask)
W = W * mask
print(W.shape)
WT = np.expand_dims(W, axis=1)
print(WT.shape)
WW = np.abs(WT * W)
print(WW.shape)
WW44 = np.array(WW.sum(axis=2), dtype='float')
print(WW44.shape)
WW44


(4, 8)
(4, 1, 8)
(4, 4, 8)
(4, 4)


array([[46.,  0.,  0., 26.],
       [ 0.,  9., 15., 21.],
       [ 0., 15., 25., 35.],
       [26., 21., 35., 91.]])

In [4]:
WW = np.zeros((W.shape[0], W.shape[0], W.shape[1]))

for i in range(W.shape[0]):
    for k in range(W.shape[0]):
        for j in range(W.shape[1]):
            WW[i, k, j] = np.abs(W[i][j] * W[k][j])
print(WW.shape)
WW44_2 = WW.sum(axis=2)
print(WW44_2.shape)
WW44_2

(4, 4, 8)
(4, 4)


array([[46.,  0.,  0., 26.],
       [ 0.,  9., 15., 21.],
       [ 0., 15., 25., 35.],
       [26., 21., 35., 91.]])

In [5]:
np.sum(WW44-WW44_2)


0.0

In [45]:
W = np.random.randint(-4, 9, 4*8).reshape(4, 8)
print(W)
WTr = 0.5 * np.mean(np.abs(W), axis=1)
W[np.where(np.abs(W) < WTr[np.newaxis].T)] = 0
np.sum(W == 0)

[[ 8 -1  2 -2  2  8  3 -4]
 [-3  3 -1 -3 -1 -4  5  0]
 [ 2  3 -1 -3  5 -4  4  3]
 [-2  8 -1  7  6  6 -3 -1]]


8