In [1]:
import numpy as np;

a = np.random.randint(1,10,16)
print(a)

[6 1 9 7 9 2 1 9 4 1 1 9 3 5 4 6]


d_syn[j_n] = syn[i_n] * (syn_len / (j_n - i_n)**N )

In [20]:
a_idx = np.arange(a.size)
n = 1
a_len = a.size**n - np.abs(a_idx[np.newaxis].T - a_idx)**n
np.fill_diagonal(a_len, 0)
print(a_len)

[[ 0 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
 [15  0 15 14 13 12 11 10  9  8  7  6  5  4  3  2]
 [14 15  0 15 14 13 12 11 10  9  8  7  6  5  4  3]
 [13 14 15  0 15 14 13 12 11 10  9  8  7  6  5  4]
 [12 13 14 15  0 15 14 13 12 11 10  9  8  7  6  5]
 [11 12 13 14 15  0 15 14 13 12 11 10  9  8  7  6]
 [10 11 12 13 14 15  0 15 14 13 12 11 10  9  8  7]
 [ 9 10 11 12 13 14 15  0 15 14 13 12 11 10  9  8]
 [ 8  9 10 11 12 13 14 15  0 15 14 13 12 11 10  9]
 [ 7  8  9 10 11 12 13 14 15  0 15 14 13 12 11 10]
 [ 6  7  8  9 10 11 12 13 14 15  0 15 14 13 12 11]
 [ 5  6  7  8  9 10 11 12 13 14 15  0 15 14 13 12]
 [ 4  5  6  7  8  9 10 11 12 13 14 15  0 15 14 13]
 [ 3  4  5  6  7  8  9 10 11 12 13 14 15  0 15 14]
 [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15  0 15]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15  0]]


In [26]:
d_a = np.dot(a_len, a)
print(d_a, d_a.shape)

[584 729 664 741 740 865 890 769 838 867 846 695 750 671 630 533] (16,)


In [27]:
d_a = np.dot(a, a_len)
print(d_a, d_a.shape)

[584 729 664 741 740 865 890 769 838 867 846 695 750 671 630 533] (16,)


In [30]:
a_mul = a * a_len
print(a_mul)
print(np.sum(a_mul, axis=0))

[[  0  15 126  91 108  22  10  81  32   7   6  45  12  15   8   6]
 [ 90   0 135  98 117  24  11  90  36   8   7  54  15  20  12  12]
 [ 84  15   0 105 126  26  12  99  40   9   8  63  18  25  16  18]
 [ 78  14 135   0 135  28  13 108  44  10   9  72  21  30  20  24]
 [ 72  13 126 105   0  30  14 117  48  11  10  81  24  35  24  30]
 [ 66  12 117  98 135   0  15 126  52  12  11  90  27  40  28  36]
 [ 60  11 108  91 126  30   0 135  56  13  12  99  30  45  32  42]
 [ 54  10  99  84 117  28  15   0  60  14  13 108  33  50  36  48]
 [ 48   9  90  77 108  26  14 135   0  15  14 117  36  55  40  54]
 [ 42   8  81  70  99  24  13 126  60   0  15 126  39  60  44  60]
 [ 36   7  72  63  90  22  12 117  56  15   0 135  42  65  48  66]
 [ 30   6  63  56  81  20  11 108  52  14  15   0  45  70  52  72]
 [ 24   5  54  49  72  18  10  99  48  13  14 135   0  75  56  78]
 [ 18   4  45  42  63  16   9  90  44  12  13 126  45   0  60  84]
 [ 12   3  36  35  54  14   8  81  40  11  12 117  42  75   0 

In [32]:
def get_dW(W, n = 1):
    a_idx = np.arange(W.size)
    a_len = W.size**n - np.abs(a_idx[np.newaxis].T - a_idx)**n
    np.fill_diagonal(a_len, 0)
    d_a = np.dot(W, a_len)

    return d_a

[584 729 664 741 740 865 890 769 838 867 846 695 750 671 630 533]


In [41]:
print(a)
dW = get_dW(a)
# print(dW / np.linalg.norm(dW))
print(dW)

[6 1 9 7 9 2 1 9 4 1 1 9 3 5 4 6]
[584 729 664 741 740 865 890 769 838 867 846 695 750 671 630 533]
